# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install
      - cypress/run:
          record: true